### ISSUE TITLE
Jobs are not inserted into solr, if the status is 'active'

### ISSUE THREAD

**Issue by cbleek** [yawik/SimpleImport#3]
@TiSiE the simple import currently does not put jobs into the solr index. Maybe it's because there is no job event triggered as we do when activate a job?

https://github.com/cross-solution/YAWIK/blob/efca22b0a7017b8e8cc60490340dbb47d8047c45/module/Jobs/src/Jobs/Controller/ManageController.php#L586

**Comment by TiSiE** [comment]
No, the solr module registers a doctrine preUpdate hook to track entities to add to the index.
That is, because in the normal Yawik workflow, a job CANNOT be INSERTED with the status "active".

There are two possibilities to solve this:
* This module: Insert the job as "created" and update the status immediately - which means two database operation for one "action"; or
* Add a "preInsert" hook in the Solr module to catch inserted jobs with the status set to "active"

The latter is preferable.

**Comment by cbleek** [comment]
@fedys do you can add the "preInsert" hook in the Solr module?

**Comment by fedys** [comment]
Yes, I can do that. I can take a look at it on Thursday morning.

**Comment by cbleek** [comment]
super!

**Comment by cbleek** [comment]
This will be done in https://github.com/yawik/Solr/issues/10
